version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    ports:
      - "8080:8080" # Замените на нужный порт
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
      - APP_PORT=8080

  redis:
    image: redis:7.0
    container_name: redis_service
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
